
name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '3.0', '3.1.x', '5.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 3.x
        uses: actions/setup-dotnet@v2
        with:
        # Semantic version range syntax or exact version of a dotnet version
         dotnet-version: '3.x'
